### ISSUE TITLE
[Bug] [V1.1.0] The edited data source, click Finish and an error will pop up

### ISSUE THREAD

**Issue by jinquanzhuang** [WeDataSphere/linkis-test#3]
The edited data source, click Finish and an error will pop up
![image](https://user-images.githubusercontent.com/101614307/159011386-a09a786e-4281-4d01-863f-52870cc73e49.png)
![image](https://user-images.githubusercontent.com/101614307/159011419-444efb95-51f3-4ce5-8d48-b2212272f663.png)

**Comment by casionone** [comment]
fixed
